/* eslint-disable no-unused-vars */

enum EGender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHERS = 'OTHERS'
}

enum ERole {
  PATIENT = 'PATIENT',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  ADMIN = 'ADMIN',
  PHARMACIST = 'PHARMACIST',
  LAB_TECHNICIAN = 'LAB_TECHNICIAN',
  ACCOUNTANT = 'ACCOUNTANT',
  HOSPITAL_ADMINISTRATOR = 'HOSPITAL_ADMINISTRATOR',
  IT_SUPPORT = 'IT_SUPPORT',
  SUPER_ADMIN = 'SUPER_ADMIN'
}

export { EGender, ERole };
